[tool.poetry]
name = "lazy-beanstalk"
authors = ["Alex Basile <basileaw@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
uvicorn = "*"
jinja2 = "*"
bs4 = ">=0.0.2"
requests = ">=2.32.3"
httpx = "*"
rich = "*"
websockets = "*"
terminaide = "^0.0.1"
chatline = "^0.0.5"

[tool.poetry.group.dev.dependencies]
pyyaml = "*"
boto3 = "*"
botocore = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
serve = "python app/server.py"
serve-container = """
sh -c 'DIR=${PWD##*/} && \
docker buildx build --no-cache -t $DIR-web . && \
docker rm -f $DIR-web 2>/dev/null || true && \
docker run --name $DIR-web -p 80:80 -v ~/.aws:/root/.aws:ro $DIR-web'
"""
ship = "python deployment/manage.py ship"
secure = "python deployment/manage.py secure"
scrap = "python deployment/manage.py scrap"

[tool.poetry.extras]
system = ["ttyd"]
