[tool.poetry]
name = "lazy-beanstalk"
authors = ["Alex Basile <basileaw@gmail.com>"]
version = "0.0.0"
description = "A simple web app to deploy to AWS Elastic Beanstalk"


[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
uvicorn = "*"
jinja2 = "*"
bs4 = ">=0.0.2"
requests = ">=2.32.3"
httpx = "*"
rich = "*"
websockets = "*"
chatline = "^0.0.5"
terminaide = {git = "https://github.com/anotherbazeinthewall/terminaide"}

[tool.poetry.group.dev.dependencies]
pyyaml = "*"
boto3 = "*"
botocore = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
serve = "python app/server.py"
serve-container = """
sh -c 'DIR=${PWD##*/} && \
docker rm -f $DIR-web || true && \
docker buildx build --force-rm=true --no-cache -t $DIR-web . && \
docker run --rm --name $DIR-web -p 8000:8000 -v ~/.aws:/root/.aws:ro $DIR-web'
"""
ship = "python deployment/manage.py ship"
secure = "python deployment/manage.py secure"
scrap = "python deployment/manage.py scrap"
