[project]
name = "lazy-beanstalk"
authors = [{ name = "Alex Basile", email = "basileaw@gmail.com" }]
version = "0.0.0"
description = "A template for deploying Python web apps to AWS Elastic Beanstalk"
requires-python = "^3.12"
dependencies = ["terminaide>=0.1.1", "chatline>=0.2.0"]

[project.optional-dependencies]
dev = ["boto3", "botocore"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
