[tool.poetry]
name = "lazy-beanstalk"
authors = ["Alex Basile <basileaw@gmail.com>"]
version = "0.0.0"
description = "A template for deploying Python web apps to AWS Elastic Beanstalk"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
terminaide = "^0.1.1"
chatline = "^0.2.0"

[tool.poetry.group.dev.dependencies]
boto3 = "*"
botocore = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
