# AWS Regional Configuration
aws:
  region: us-west-2
  platform: "64bit Amazon Linux 2023 v4.4.2 running Docker"
  tags:
    Environment: development
    Project: ${PROJECT_NAME}
    ManagedBy: deployment-scripts

# Application Configuration
application:
  name: ${PROJECT_NAME}
  environment: ${PROJECT_NAME}-env
  description: "${PROJECT_NAME} Application"

# Instance Configuration
instance:
  type: t3.micro
  elb_type: application
  autoscaling:
    min_instances: 1
    max_instances: 1

# IAM Configuration
iam:
  # Service role for Elastic Beanstalk
  service_role_name: ${PROJECT_NAME}-eb-role
  service_role_policies:
    # Trust policy JSON file in deployment/policies/
    trust_policy: eb-trust-policy.json
    # AWS-managed policies to attach
    managed_policies:
      - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
      - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth

  # Instance profile and role for EC2 instances
  instance_profile_name: ${PROJECT_NAME}-ec2-profile
  instance_role_name: ${PROJECT_NAME}-ec2-role
  instance_role_policies:
    # Trust policy JSON file in deployment/policies/
    trust_policy: ec2-trust-policy.json
    # AWS-managed policies to attach
    managed_policies:
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
