# configurations/config.yml

## AWS Regional Configuration
aws:
  region: ${AWS_REGION}
  platform: ${LATEST_DOCKER_PLATFORM}
  tags:
    Environment: development
    Project: ${PROJECT_NAME}
    ManagedBy: deployment-scripts

## Application Configuration
application:
  name: ${PROJECT_NAME}
  environment: ${PROJECT_NAME}-env
  description: "${PROJECT_NAME} Application"

## Instance Configuration
instance:
  type: t4g.nano
  elb_type: application
  autoscaling:
    min_instances: 1
    max_instances: 1

## IAM Configuration
iam:
  ### Service role for Elastic Beanstalk
  service_role_name: ${PROJECT_NAME}-eb-role
  service_role_policies:
    trust_policy: eb-trust-policy.json
    managed_policies:
      - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
      - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
  
  # Instance profile and role for EC2 instances
  instance_profile_name: ${PROJECT_NAME}-ec2-profile
  instance_role_name: ${PROJECT_NAME}-ec2-role
  instance_role_policies:
    trust_policy: ec2-trust-policy.json
    managed_policies:
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
    custom_policies:
      - bedrock.json

## OIDC Configuration
### Required environment variables: OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_ISSUER,
### OIDC_AUTH_ENDPOINT, OIDC_TOKEN_ENDPOINT, OIDC_USERINFO_ENDPOINT
oidc:
  client_id: ${OIDC_CLIENT_ID}
  client_secret: ${OIDC_CLIENT_SECRET}
  issuer: ${OIDC_ISSUER}
  endpoints:
    authorization: ${OIDC_AUTH_ENDPOINT}
    token: ${OIDC_TOKEN_ENDPOINT}
    userinfo: ${OIDC_USERINFO_ENDPOINT}
  
  ### Default session settings
  session:
    cookie_name: federate_id_token
    timeout: 36000
    scope: openid

## EB CLI Configuration
elasticbeanstalk_cli:
  branch-defaults:
    main:
      environment: ${PROJECT_NAME}-env
      group_suffix: null
  global:
    application_name: ${PROJECT_NAME}
    branch: null
    default_ec2_keyname: null
    default_platform: ${EB_CLI_PLATFORM}
    default_region: ${AWS_REGION}
    include_git_submodules: true
    instance_profile: null
    platform_name: null
    platform_version: null
    profile: null
    repository: null
    sc: git
    workspace_type: Application